// <auto-generated />
using System;
using GestionBares.Models.AlmacenModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestionBares.Migrations.AlmacenDb
{
    [DbContext(typeof(AlmacenDbContext))]
    [Migration("20190521140906_AgregandoControles")]
    partial class AgregandoControles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GestionBares.Models.AlmacenModels.Control", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BarId");

                    b.Property<double>("Cantidad");

                    b.Property<DateTime>("Fecha");

                    b.Property<int>("ProductoId");

                    b.HasKey("Id");

                    b.ToTable("Controles");
                });

            modelBuilder.Entity("GestionBares.Models.AlmacenModels.Existencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Cantidad");

                    b.Property<string>("CodigoProducto");

                    b.HasKey("Id");

                    b.ToTable("Existencias");

                    b.HasData(
                        new { Id = 1, Cantidad = 10.0, CodigoProducto = "1" },
                        new { Id = 2, Cantidad = 20.0, CodigoProducto = "2" },
                        new { Id = 3, Cantidad = 30.0, CodigoProducto = "3" },
                        new { Id = 4, Cantidad = 10.0, CodigoProducto = "4" },
                        new { Id = 5, Cantidad = 20.0, CodigoProducto = "5" },
                        new { Id = 6, Cantidad = 30.0, CodigoProducto = "6" },
                        new { Id = 7, Cantidad = 10.0, CodigoProducto = "7" },
                        new { Id = 8, Cantidad = 10.0, CodigoProducto = "8" },
                        new { Id = 9, Cantidad = 10.0, CodigoProducto = "9" },
                        new { Id = 10, Cantidad = 10.0, CodigoProducto = "10" },
                        new { Id = 11, Cantidad = 10.0, CodigoProducto = "11" },
                        new { Id = 12, Cantidad = 10.0, CodigoProducto = "12" },
                        new { Id = 13, Cantidad = 10.0, CodigoProducto = "13" },
                        new { Id = 14, Cantidad = 10.0, CodigoProducto = "14" },
                        new { Id = 15, Cantidad = 10.0, CodigoProducto = "15" },
                        new { Id = 16, Cantidad = 10.0, CodigoProducto = "16" },
                        new { Id = 17, Cantidad = 10.0, CodigoProducto = "17" },
                        new { Id = 18, Cantidad = 10.0, CodigoProducto = "18" },
                        new { Id = 19, Cantidad = 10.0, CodigoProducto = "19" },
                        new { Id = 20, Cantidad = 10.0, CodigoProducto = "20" },
                        new { Id = 21, Cantidad = 10.0, CodigoProducto = "21" },
                        new { Id = 22, Cantidad = 10.0, CodigoProducto = "22" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
